apiVersion: v1
kind: Namespace
metadata:
  name: demo
  labels:
    # pod-security.kubernetes.io/enforce: baseline
    # pod-security.kubernetes.io/enforce-version: latest
    # pod-security.kubernetes.io/warn: baseline
    # pod-security.kubernetes.io/warn-version: latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: demo
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      securityContext:
        seccompProfile:
          type: Unconfined
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
